package masterClass.java17;

import java.math.BigDecimal;

public record Product(String name,
		BigDecimal cost,
		String type) {

	//By Default the constructor generated by the compiler are called canonical Constructor
	
	public Product {
		//here we can add validation to the input parmeters
		if(name == null || name.isBlank()) {
			throw new IllegalArgumentException("name is not valid");
		}
		
		if(cost.compareTo(BigDecimal.ZERO)<=0) {
			throw new IllegalArgumentException("cost is not valid");
		}
	}
	
	//to create a custom constructor
	public Product(String name, BigDecimal cost){
		this(name,cost,"General");
	}
	
}
